### ISSUE TITLE
Add VNM: Venom

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#1]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x804ea14b08dec488e5b0bc408f23eef107fe3717
Token Name (from contract): Venom
Token Decimals (from contract): 18
Token Symbol (from contract): VNM
Uniswap V2 Pair Address of Token: 0x04411209d86e742ec3e94af868cb050edb594d37

Link to the official homepage of token: https://venomcrypto.io
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/venom-vnm/

**Comment by olivbau** [comment]
For the token to be added, it must be on Coingecko

**Comment by MrLightspeed** [comment]
Should the master template be revised to only provide the CG link?

**Comment by olivbau** [comment]
I've modified the template,
I specifically need the token to be on coingecko for this to work.

**Comment by MrLightspeed** [comment]
Thank you - see, we've made it better. I can resubmit when the listing comes through as it's not expected to be done for a courple weeks.
