### ISSUE TITLE
Add PLU: Pluton

### ISSUE THREAD

**Issue by frozon** [sonarwatch/token-lists#11]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum
* Token Address: 0xd8912c10681d8b21fd3742244f44658dba12264e
* Token Name (from contract): Pluton
* Token Decimals (from contract): 18
* Token Symbol (from contract): Plu
* AMM Pair link: 0xe11ee9c18d03b43d6a7fc53e51aedda8451e837a
* Link to the official homepage of token: https://plutus.it
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/pluton

**Comment by olivbau** [comment]
auto added
