### ISSUE TITLE
Add {ORACLE}: {ORACLE AI}

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#12]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum
* Token Address: 0x57B49219614859176Ddb029298486B6c30193Cbd
* Token Name (from contract): Oracle AI
* Token Decimals (from contract): 18
* Token Symbol (from contract): ORACLE
* AMM Pair link: 0xa4d6e4B0fa15592D76E9C323913425A17030b490
* Link to the official homepage of token: https://oracleai.app
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/oracle-ai

**Comment by olivbau** [comment]
added
