### ISSUE TITLE
Add {clARB}: {Cloned Arbitrum}

### ISSUE THREAD

**Issue by dmark1415** [sonarwatch/token-lists#13]
- [ ] I understand that token listing is not required to use the Uniswap Interface with a token.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Solana
* Token Address: 9cMWa1wuWcio3vgEpiFg7PqKbcoafuUw5sLYFkXJ2J8M
* Token Name (from contract): Cloned Arbitrum
* Token Decimals (from contract): 8
* Token Symbol (from contract): clARB
* AMM Pair link: https://markets.clone.so/trade/arbitrum
* Link to the official homepage of token: https://clone.so/
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/clone-protocol-clarb

**Comment by olivbau** [comment]
added
