### ISSUE TITLE
Add {clOP}: {Cloned Optimism}

### ISSUE THREAD

**Issue by dmark1415** [sonarwatch/token-lists#14]
- [ ] I understand that token listing is not required to use the Uniswap Interface with a token.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Solana
* Token Address: 4cwVHQtwiK7r9aAUsu4cetk1JtLWPymopWcpTSsihCdL
* Token Name (from contract): Cloned Optimism
* Token Decimals (from contract): 8
* Token Symbol (from contract): clOP
* AMM Pair link: https://markets.clone.so/trade/optimism
* Link to the official homepage of token: https://clone.so/
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/clone-protocol-clop

**Comment by olivbau** [comment]
added
