### ISSUE TITLE
Add {KNINE}: {K9 Finance DAO}

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#15]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum
* Token Address: 0x91fbB2503AC69702061f1AC6885759Fc853e6EaE
* Token Name (from contract): K9 Finance DAO
* Token Decimals (from contract): 18
* Token Symbol (from contract): KNINE
* AMM Pair link: https://v2.info.uniswap.org/pair/0xd7cef1e0c02b50e9c5852f47736880b66e50acde
* Link to the official homepage of token: https://www.k9finance.com/
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/k9-finance-dao

**Comment by olivbau** [comment]
added!
