### ISSUE TITLE
Add {BOBBY}: {Kennedy Coin}

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#17]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum
* Token Address: 0xa462bde22d98335e18a21555b6752db93a937cff
* Token Name (from contract): Kennedy Memecoin
* Token Decimals (from contract): 18
* Token Symbol (from contract): BOBBY
* AMM Pair link: https://v2.info.uniswap.org/pair/0xa2672a414c79677162ef9df73b2352dac4dded65
* Link to the official homepage of token: https://buybobby.com
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/independence-token

**Comment by MrLightspeed** [comment]
@olivbau Tagging - and thank you for all you do!

**Comment by olivbau** [comment]
Added automaticaly from coingecko
