### ISSUE TITLE
Add BAD: BAD IDEA AI

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#2]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x32b86b99441480a7e5bd3a26c124ec2373e3f015
Token Name (from contract): Bad Idea AI
Token Decimals (from contract): 18
Token Symbol (from contract): BAD
Uniswap V2 Pair Address of Token: 0x29c830864930c897efa2b9e9851342187b82010e

Link to the official homepage of token: https://badidea.ai
Link CoinGecko page of token: https://www.coingecko.com/en/coins/bad-idea-ai

**Comment by olivbau** [comment]
For the token to be added, it must be on Coingecko

**Comment by MrLightspeed** [comment]
Should come through in the next couple days on this one. Perhaps the template should not suggest it's either CMC or CG?

**Comment by olivbau** [comment]
I've modified the template,
I specifically need the token to be on coingecko for this to work.

**Comment by MrLightspeed** [comment]
This one is in pending status with coingecko - would like to wait 24 hours to see if it comes through if it works with you.

**Comment by MrLightspeed** [comment]
> 

Hi! The token is now listed on Coingecko and I added the link.

**Comment by olivbau** [comment]
added

**Comment by MrLightspeed** [comment]
Thanks for the support - glad to see the project a part of the Sonarwatch Portfolio Tracker and suite of products.
