### ISSUE TITLE
Add FUKU: Fuku-Kun

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#20]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum
* Token Address: 0x1001271083c249bd771e1bb76c22d935809a61ee
* Token Name (from contract): Fuku-Kun
* Token Decimals (from contract): 9
* Token Symbol (from contract): FUKU
* AMM Pair link: https://app.uniswap.org/explore/tokens/ethereum/0xb3014e8171155e90aa2d9ca995db069a89aabe06
* Link to the official homepage of token: https://fukutoken.xyz/
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/fuku-kun

**Comment by MrLightspeed** [comment]
@olivbau Thank you!

**Comment by olivbau** [comment]
Np, btw as soon as it on coingecko, it'll be added automatically in ~ 24h

**Comment by MrLightspeed** [comment]
@olivbau Oh! Does that mean these submissions aren't necessary? If so, this is good to know and thank you.
