### ISSUE TITLE
Add wPAW: PAW

### ISSUE THREAD

**Issue by ghost** [sonarwatch/token-lists#21]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum | Polygon | BNB | Base | Arbitrum (multichain token with one CA)
* Token Address: 0xc11158c5da9db1d553ed28f0c2ba1cbedd42cfcb
* Token Name (from contract): Wrapped PAW
* Token Decimals (from contract): 18
* Token Symbol (from contract): wPAW
* AMM Pair link:
UniSwap (ETH) | https://app.uniswap.org/explore/tokens/ethereum/0xc11158c5dA9db1D553ED28f0C2BA1CbEDD42CFcb
UniSwap (Arbitrum) | https://app.uniswap.org/explore/tokens/arbitrum/0xc11158c5dA9db1D553ED28f0C2BA1CbEDD42CFcb
UniSwap (Base) | https://app.uniswap.org/explore/tokens/base/0xc11158c5dA9db1D553ED28f0C2BA1CbEDD42CFcb
PancakeSwap (BNB) | https://pancakeswap.finance/info/tokens/0xc11158c5da9db1d553ed28f0c2ba1cbedd42cfcb
QuickSwap (Polygon) |  
* Link to the official homepage of token: https://pawchain.net
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/paw

**Comment by olivbau** [comment]
It's on ETH, base, bnb, polygon and arbitrum
