### ISSUE TITLE
Add {Afc }: {Africash}

### ISSUE THREAD

**Issue by mantogo** [sonarwatch/token-lists#22]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Binance smart chain 
* Token Address:0x496d8C49B31ffC18c2bD9839F93BAeF771Ab1dF5
* Token Name (from contract): Africash 
* Token Decimals (from contract): 18
* Token Symbol (from contract): Afc 
* AMM Pair link: Afc/TKP
* Link to the official homepage of token: https://africashtoken.com
* Link to CoinGecko page of token: https://www.geckoterminal.com/bsc/pools/0xf278825aba90bad40b8c29df1d9f9037dbc4ca73

**Comment by mantogo** [comment]
add token to sonar watch

**Comment by mantogo** [comment]
add token to sonar watch

**Comment by olivbau** [comment]
If it's available on coingecko, it'll be automatically added
For now, liquidity is too low

**Comment by mantogo** [comment]
ok. so being available on gecko terminal is not sufficient?

**Comment by olivbau** [comment]
No, it's not
