### ISSUE TITLE
Add {kySOL}: {Kyros Restaked SOL}

### ISSUE THREAD

**Issue by zwifta** [sonarwatch/token-lists#23]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Solana
* Token Address:kySo1nETpsZE2NWe5vj2C64mPSciH1SppmHb4XieQ7B
* Token Name (from contract):Kyros Restaked SOL
* Token Decimals (from contract):9
* Token Symbol (from contract):kySOL
* AMM Pair link:https://raydium.io/clmm/create-position/?pool_id=529FAHK9P4bZtUtG2qpGemdttE9jDNSEohH5HzoAHMXJ
* Link to the official homepage of token:kyros.fi
* Link to CoinGecko page of token:

**Comment by olivbau** [comment]
added
