### ISSUE TITLE
Add {LYNX}: {Lynx Tech}

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#6]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum
* Token Address: 0x80d186b4c786ea66592b2c52e2004ab10cfe4cf3
* Token Name (from contract): LYNX
* Token Decimals (from contract): 18
* Token Symbol (from contract): LYNX
* AMM Pair link: https://app.uniswap.org/#/swap?outputCurrency=0x80d186b4c786ea66592b2c52e2004ab10cfe4cf3
* Link to the official homepage of token: https://lynxtech.io
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/lynx-2

**Comment by olivbau** [comment]
added
