### ISSUE TITLE
Add {BAD}: {BAD IDEA AI}

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#7]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum
* Token Address:  0x32b86b99441480a7E5BD3A26c124ec2373e3F015
* Token Name (from contract): BAD IDEA AI
* Token Decimals (from contract): 18
* Token Symbol (from contract): BAD
* AMM Pair link: https://app.uniswap.org/#/swap?outputCurrency=0x32b86b99441480a7e5bd3a26c124ec2373e3f015
* Link to the official homepage of token: https://badidea.ai
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/bad-idea-ai

**Comment by olivbau** [comment]
automatically added from coingecko
