### ISSUE TITLE
Add {CMOS}: {CoinMerge OS}

### ISSUE THREAD

**Issue by MrLightspeed** [sonarwatch/token-lists#8]
- [X] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum 
* Token Address: 0x87869A9789291A6cEC99f3c3Ef2fF71fcEb12a8e
* Token Name (from contract): CoinMerge OS
* Token Decimals (from contract): 9
* Token Symbol (from contract): CMOS
* AMM Pair link: https://app.uniswap.org/#/swap?outputCurrency=0x87869a9789291a6cec99f3c3ef2ff71fceb12a8e
* Link to the official homepage of token: https://app.coinmerge.io/
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/coinmerge-os/

**Comment by olivbau** [comment]
added
