### ISSUE TITLE
Add JNE: Jake Newman Enterprises

### ISSUE THREAD

**Issue by erc20student** [sonarwatch/token-lists#9]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

* Token Network: Ethereum
* Token Address: 0x9657477ac915f56ca87c253db1320218ec2d5ddd
* Token Name (from contract): Jake Newman Enterprises
* Token Decimals (from contract): 18
* Token Symbol (from contract): JNE
* AMM Pair link: 0x08e7b78041880d8a1f9e98448be2cf1293be85e4
* Link to the official homepage of token: https://www.jakenewman.enterprises
* Link to CoinGecko page of token: https://www.coingecko.com/en/coins/jake-newman-enterprises

**Comment by olivbau** [comment]
automatically added
